### ISSUE TITLE
isort incompatible with ruff? 

### ISSUE THREAD

**Issue by vivbak** [populationgenomics/cpg-python-template-repo#13]
There were linting issues in the following PR https://github.com/populationgenomics/transfer-private/pull/47 

Specifically 
```
pre-commit run --files clear_test_dataset_on_metamist.py                                                                                                                                                               
check yaml...........................................(no files to check)Skipped
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
check for case conflicts.................................................Passed
check for merge conflicts................................................Passed
detect private key.......................................................Passed
debug statements (python)................................................Passed
check for added large files..............................................Passed
markdownlint.........................................(no files to check)Skipped
isort (python)...........................................................Failed
- hook id: isort
- files were modified by this hook

Fixing /Users/vivian/Desktop/Code/transfer-private/thousand-genomes/clear_test_dataset_on_metamist.py

black....................................................................Passed
ruff.....................................................................Failed
- hook id: ruff
- files were modified by this hook

Found 1 error (1 fixed, 0 remaining).

mypy.....................................................................Passed 
```

Basically, isort is incompatible with ruff. The modifications to the files as a result of isort will subsequently cause failures in ruff and vice versa.

**Comment by MattWellie** [comment]
Hah, catastrophic. I guess the fix is seeing if ruff supports all the primary/secondary configs and just using ruff's isort implementation, or skipping the ruff isort checks
https://docs.astral.sh/ruff/settings/#isort

**Comment by illusional** [comment]
Ooh yeah, sorry I noticed this in a related PR for tob-wgs: https://github.com/populationgenomics/tob-wgs/pull/173, but hadn't had time to PR back. This is also partially related to the `--fix` add in the pre-commit, something we probably don't want to do for ruff (despite our other hooks modifying in place) - as that's not the default behaviour off other type checking tools.

I've added a PR #14 to address this, and unrelated will follow-up with directions on adding a new cpg-id-checker: https://github.com/populationgenomics/pre-commits/pull/1
